// MOSIntegration data — extends AgentRow with category field
// Agents come from MOS (complete inventory, includes inactive)
// AI apps come from audit logs (last 30 days activity only)

export type MOSCategory = 'Agent' | 'AI app'

export type MOSAgentRow = {
  name: string
  category: MOSCategory
  type: 'app' | 'user'
  icon?: 'copilot' | 'excel' | 'teams' | 'slack' | 'salesforce' | 'custom'
  initials?: string
  status: 'Active' | 'Inactive'
  agentId: string
  riskLevel: 'High' | 'Medium' | 'Low' | 'None'
  riskType: string
  sensitiveActivityTrend: number[] | null
  dataProtection: string
  dataCompliance: string
}

export const mosRows: MOSAgentRow[] = [
  // ── Agents (from MOS — complete inventory) ──────────────────
  // Active agents with activity
  {
    name: 'M&A Deal Room Assistant',
    category: 'Agent',
    type: 'app',
    icon: 'copilot',
    status: 'Active',
    agentId: 'Fin.M&A.T_fac75f59-d4d7-88...',
    riskLevel: 'High',
    riskType: 'Oversharing',
    sensitiveActivityTrend: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 0, 15, 30, 25, 0],
    dataProtection: '0 Policies',
    dataCompliance: '0 Policies',
  },
  {
    name: 'Executive Payroll Auditor',
    category: 'Agent',
    type: 'app',
    icon: 'excel',
    status: 'Active',
    agentId: 'HR.Exec.T_45a2ccdc-ec13-a4...',
    riskLevel: 'High',
    riskType: 'Exfiltration',
    sensitiveActivityTrend: [0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 30, 0, 0, 0, 0, 0],
    dataProtection: '0 Policies',
    dataCompliance: '0 Policies',
  },
  {
    name: 'Patent Application Generator',
    category: 'Agent',
    type: 'app',
    icon: 'copilot',
    status: 'Active',
    agentId: 'Legal.IP.T_9d6e2bfd-3cfd-28...',
    riskLevel: 'High',
    riskType: 'Oversharing, Exfiltration',
    sensitiveActivityTrend: [0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 10, 30, 0, 20, 15, 0],
    dataProtection: '0 Policies',
    dataCompliance: '0 Policies',
  },
  {
    name: 'Customer PII Retriever',
    category: 'Agent',
    type: 'user',
    initials: 'S',
    status: 'Active',
    agentId: 'Sup.PII.78942ebe-0325-471e...',
    riskLevel: 'High',
    riskType: 'Oversharing',
    sensitiveActivityTrend: [0, 0, 0, 0, 2, 20, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    dataProtection: '0 Policies',
    dataCompliance: '0 Policies',
  },
  {
    name: 'Source Code Vulnerability Scanner',
    category: 'Agent',
    type: 'user',
    initials: 'D',
    status: 'Active',
    agentId: 'Dev.Sec.21adf640-fdfa-42d3...',
    riskLevel: 'High',
    riskType: 'Exfiltration',
    sensitiveActivityTrend: [10, 20, 5, 0, 0, 15, 0, 0, 30, 0, 0, 10, 15, 0, 0, 0],
    dataProtection: '0 Policies',
    dataCompliance: '0 Policies',
  },
  {
    name: 'Litigation Hold Search',
    category: 'Agent',
    type: 'user',
    initials: 'L',
    status: 'Active',
    agentId: 'Leg.Hold.157745c9-87c3-42e5...',
    riskLevel: 'High',
    riskType: 'Oversharing',
    sensitiveActivityTrend: [5, 5, 5, 10, 20, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    dataProtection: '0 Policies',
    dataCompliance: '0 Policies',
  },
  {
    name: 'TravelBot',
    category: 'Agent',
    type: 'app',
    icon: 'copilot',
    status: 'Active',
    agentId: 'Travel.Bot.T_bbf5b74e-e8e4...',
    riskLevel: 'Medium',
    riskType: 'Oversharing',
    sensitiveActivityTrend: [0, 0, 3, 5, 2, 0, 0, 0],
    dataProtection: '1 Policy',
    dataCompliance: '0 Policies',
  },
  {
    name: 'AborseAgentJan092026',
    category: 'Agent',
    type: 'app',
    icon: 'custom',
    status: 'Active',
    agentId: 'Aborse.Jan.22...',
    riskLevel: 'Low',
    riskType: 'Oversharing',
    sensitiveActivityTrend: [0, 0, 0, 2, 5, 1, 0, 0],
    dataProtection: '1 Policy',
    dataCompliance: '0 Policies',
  },
  {
    name: '01/20/2026-AborseAgent',
    category: 'Agent',
    type: 'app',
    icon: 'custom',
    status: 'Active',
    agentId: 'Aborse.782h-28...',
    riskLevel: 'None',
    riskType: 'No data available',
    sensitiveActivityTrend: null,
    dataProtection: '0 Policies',
    dataCompliance: '0 Policies',
  },
  {
    name: 'ADO Agent POC',
    category: 'Agent',
    type: 'app',
    icon: 'custom',
    status: 'Active',
    agentId: 'ADO.POC.992-11...',
    riskLevel: 'None',
    riskType: 'No data available',
    sensitiveActivityTrend: null,
    dataProtection: '0 Policies',
    dataCompliance: '0 Policies',
  },
  // Inactive agents (from MOS inventory — no activity data)
  {
    name: 'HR Benefits Lookup',
    category: 'Agent',
    type: 'app',
    icon: 'copilot',
    status: 'Inactive',
    agentId: 'HR.Ben.T_c4a91e7d-2f58-4b...',
    riskLevel: 'None',
    riskType: '—',
    sensitiveActivityTrend: null,
    dataProtection: '0 Policies',
    dataCompliance: '0 Policies',
  },
  {
    name: 'IT Helpdesk Assistant',
    category: 'Agent',
    type: 'app',
    icon: 'teams',
    status: 'Inactive',
    agentId: 'IT.Help.T_8e2b3f91-a4c7-5d...',
    riskLevel: 'None',
    riskType: '—',
    sensitiveActivityTrend: null,
    dataProtection: '1 Policy',
    dataCompliance: '0 Policies',
  },
  {
    name: 'Onboarding Buddy',
    category: 'Agent',
    type: 'app',
    icon: 'copilot',
    status: 'Inactive',
    agentId: 'HR.Onb.T_1f5a8c2e-b7d4-6e...',
    riskLevel: 'None',
    riskType: '—',
    sensitiveActivityTrend: null,
    dataProtection: '0 Policies',
    dataCompliance: '0 Policies',
  },
  {
    name: 'Sales Forecast Predictor',
    category: 'Agent',
    type: 'app',
    icon: 'salesforce',
    status: 'Inactive',
    agentId: 'Sales.FC.T_7d3e9a1b-c5f2-8g...',
    riskLevel: 'None',
    riskType: '—',
    sensitiveActivityTrend: null,
    dataProtection: '0 Policies',
    dataCompliance: '0 Policies',
  },
  {
    name: 'Compliance FAQ Bot',
    category: 'Agent',
    type: 'app',
    icon: 'copilot',
    status: 'Inactive',
    agentId: 'Comp.FAQ.T_2b6c4d8e-f1a3-9h...',
    riskLevel: 'None',
    riskType: '—',
    sensitiveActivityTrend: null,
    dataProtection: '2 Policies',
    dataCompliance: '1 Policy',
  },
  {
    name: 'Meeting Notes Summarizer',
    category: 'Agent',
    type: 'app',
    icon: 'teams',
    status: 'Inactive',
    agentId: 'Meet.Sum.T_4e8f2a5c-d7b1-0i...',
    riskLevel: 'None',
    riskType: '—',
    sensitiveActivityTrend: null,
    dataProtection: '0 Policies',
    dataCompliance: '0 Policies',
  },
  {
    name: 'Contract Review Agent',
    category: 'Agent',
    type: 'app',
    icon: 'copilot',
    status: 'Inactive',
    agentId: 'Legal.Rev.T_6a1b3c5d-e8f2-1j...',
    riskLevel: 'None',
    riskType: '—',
    sensitiveActivityTrend: null,
    dataProtection: '0 Policies',
    dataCompliance: '0 Policies',
  },

  // ── AI Apps (from audit logs — last 30 days activity) ────────
  {
    name: 'Microsoft 365 Copilot',
    category: 'AI app',
    type: 'app',
    icon: 'copilot',
    status: 'Active',
    agentId: 'M365.Copilot.T_a1b2c3d4-e5...',
    riskLevel: 'Low',
    riskType: 'Oversharing',
    sensitiveActivityTrend: [2, 3, 1, 4, 2, 3, 1, 2, 3, 4, 2, 1, 3, 2, 4, 3],
    dataProtection: '3 Policies',
    dataCompliance: '2 Policies',
  },
  {
    name: 'Security Copilot',
    category: 'AI app',
    type: 'app',
    icon: 'copilot',
    status: 'Active',
    agentId: 'Sec.Copilot.T_f6g7h8i9-j0...',
    riskLevel: 'None',
    riskType: 'No data available',
    sensitiveActivityTrend: [0, 0, 0, 1, 0, 0, 0, 0],
    dataProtection: '2 Policies',
    dataCompliance: '1 Policy',
  },
  {
    name: 'Fabric Copilot',
    category: 'AI app',
    type: 'app',
    icon: 'copilot',
    status: 'Active',
    agentId: 'Fabric.Cop.T_k1l2m3n4-o5...',
    riskLevel: 'None',
    riskType: 'No data available',
    sensitiveActivityTrend: [0, 0, 1, 0, 0, 2, 0, 0],
    dataProtection: '1 Policy',
    dataCompliance: '1 Policy',
  },
  {
    name: 'Q3 Financial Earnings Bot',
    category: 'AI app',
    type: 'app',
    icon: 'excel',
    status: 'Active',
    agentId: 'Fin.Earn.T_20c3fe71-eb61-d5...',
    riskLevel: 'High',
    riskType: 'Unethical',
    sensitiveActivityTrend: [0, 0, 15, 0, 0, 0, 20, 0, 0, 0, 0, 0, 8, 0, 0, 0],
    dataProtection: '0 Policies',
    dataCompliance: '0 Policies',
  },
  {
    name: 'Accounting Agent',
    category: 'AI app',
    type: 'app',
    icon: 'copilot',
    status: 'Active',
    agentId: 'Acct.Agent.33...',
    riskLevel: 'Medium',
    riskType: 'Exfiltration',
    sensitiveActivityTrend: [0, 5, 10, 5, 0],
    dataProtection: '2 Policies',
    dataCompliance: '1 Policy',
  },
  {
    name: 'Azure OpenAI Chat App',
    category: 'AI app',
    type: 'app',
    icon: 'custom',
    status: 'Active',
    agentId: 'Azure.OAI.T_p6q7r8s9-t0...',
    riskLevel: 'Low',
    riskType: 'Oversharing',
    sensitiveActivityTrend: [0, 0, 0, 3, 1, 0, 2, 0],
    dataProtection: '1 Policy',
    dataCompliance: '0 Policies',
  },
  {
    name: 'Contoso RAG Pipeline',
    category: 'AI app',
    type: 'app',
    icon: 'custom',
    status: 'Active',
    agentId: 'Contoso.RAG.T_u1v2w3x4-y5...',
    riskLevel: 'High',
    riskType: 'Exfiltration',
    sensitiveActivityTrend: [0, 0, 0, 0, 10, 25, 0, 0, 5, 0, 15, 0, 0, 20, 0, 0],
    dataProtection: '0 Policies',
    dataCompliance: '0 Policies',
  },
  {
    name: 'Customer Insights Engine',
    category: 'AI app',
    type: 'app',
    icon: 'custom',
    status: 'Active',
    agentId: 'CustIns.T_z6a7b8c9-d0...',
    riskLevel: 'None',
    riskType: 'No data available',
    sensitiveActivityTrend: [0, 0, 0, 0, 0, 1, 0, 0],
    dataProtection: '1 Policy',
    dataCompliance: '1 Policy',
  },
]
